push code to vps

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -2,6 +2,7 @@ name: CI/CD # Node.js CI/CD Application
 on:
     push:
         branches: [origin/nodejs_react]
+
 jobs:
     test:
         name: Run Node.js Tests
@@ -120,22 +121,22 @@ jobs:
                       # Dọn dẹp các image cũ không dùng đến để tránh đầy ổ cứng
                       docker image prune -f
                       
-            - name: Trigger frontend pipeline
-              if: success()
-              run: |
-                HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
-                  -H "Authorization: Bearer ${{ secrets.MY_PAT_TOKEN }}" \
-                  -H "Accept: application/vnd.github+json" \
-                  -H "X-GitHub-Api-Version: 2022-11-28" \
-                  https://api.github.com/repos/${{ github.repository }}/dispatches \
-                  -d '{"event_type":"backend_deployed"}')
+            # - name: Trigger frontend pipeline
+            #   if: success()
+            #   run: |
+            #     HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            #       -H "Authorization: Bearer ${{ secrets.MY_PAT_TOKEN }}" \
+            #       -H "Accept: application/vnd.github+json" \
+            #       -H "X-GitHub-Api-Version: 2022-11-28" \
+            #       https://api.github.com/repos/${{ github.repository }}/dispatches \
+            #       -d '{"event_type":"backend_deployed"}')
                 
-                echo "HTTP Status Code: $HTTP_CODE"
+            #     echo "HTTP Status Code: $HTTP_CODE"
                 
-                if [ "$HTTP_CODE" = "204" ]; then
-                  echo "✅ Frontend pipeline triggered successfully"
-                else
-                  echo "❌ Failed to trigger. HTTP code: $HTTP_CODE"
-                  exit 1
-                fi
+            #     if [ "$HTTP_CODE" = "204" ]; then
+            #       echo "✅ Frontend pipeline triggered successfully"
+            #     else
+            #       echo "❌ Failed to trigger. HTTP code: $HTTP_CODE"
+            #       exit 1
+            #     fi
 
